### ISSUE TITLE
JNI WriteShorts and ReadShorts error in type?

### ISSUE THREAD

**Issue by rfermontero** [philburk/portaudio-java#5]
Hey! Thanks for this amazing lib, I'm doing a strong usage of it (But I've ported it to kotlin)

I have been using as it is for a while with java 20, but now I'm compiling and running in java 21 JVM and I'm having the following issue:

```
checked_jni_ReleaseShortArrayElements: release array failed bounds check, incorrect pointer returned ? array: 0x0000000280b4e2a0 carray: 0x0000000129eed820
FATAL ERROR in native method: checked_jni_ReleaseShortArrayElements: failed bounds check
   at com.portaudio.BlockingStream.readShorts(Native Method)
   at com.portaudio.BlockingStream.read(BlockingStream.kt:114)
   at org.example.providers.PortAudioRcuAudioProvider$BlockingStreamAdapter.read(PortAudioProvider.kt:208)
   at org.example.providers.PortAudioRcuAudioProvider.read(PortAudioProvider.kt:55)
   at org.example.provider$startAudioReading$1.invokeSuspend(Provider.kt:84)
   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
   at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

I think the problem is in the JNI C:

```
JNIEXPORT jboolean JNICALL Java_com_portaudio_BlockingStream_writeShorts
  (JNIEnv *env, jobject blockingStream, jfloatArray buffer, jint numFrames)

JNIEXPORT jboolean JNICALL Java_com_portaudio_BlockingStream_readShorts
  (JNIEnv *env, jobject blockingStream, jfloatArray buffer, jint numFrames)
```

Should not be jshortArray for both jfloatArray parameters?

**Comment by philburk** [comment]
Thanks for spotting this. It is almost certainly an error as you describe.

In the HEADER com_portaudio_BlockingStream.h it is declared as jshortArray.
```
JNIEXPORT jboolean JNICALL Java_com_portaudio_BlockingStream_writeShorts
  (JNIEnv *, jobject, jshortArray, jint);
```

In com_portaudio_BlockingStream.c  it is declared as jfloatArray.
```
JNIEXPORT jboolean JNICALL Java_com_portaudio_BlockingStream_writeShorts
  (JNIEnv *env, jobject blockingStream, jfloatArray buffer, jint numFrames) { ... }
```

I am surprised it even compiled.

**Comment by philburk** [comment]
> (But I've ported it to kotlin)

Interesting! Check out this related project.  https://github.com/philburk/kc-audio-bridge
I am planning to use PortAudio for the Kotlin native target.
